version: "2"
services:
  web:
    image: zr2d2/flagship_walk:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4567:80"
    networks:
      - webnet
networks:
  webnet: